apiVersion: v1
kind: ReplicationController
metadata: 
       name: myapp-re
spec:
        replicas: 3
        template:
                 metadata: 
                       name: myapp-pod
                       labels:
                               type: frontend
                 spec:
                         containers:
                                 - name: myapp-con
                                   image: nginx
        selector:
                type: frontend
